addpath('/usr3/graduate/valpasq/TSCode/Tools/export_fig/');

h = get(0,'children');
 
for i=1:length(h)
  %saveas(h(i), [num2str(N_row) '-' num2str(N_col) 'figureCCDC' num2str(i)], 'jpg');
 
  %set(h(i),'Color','white');
  
  if i==1
  export_fig(h(i),...
      [num2str(N_row) '-' num2str(N_col) 'figure_TZ'], ...
      '-painters', ...
      '-jpg', ...
      '-r72');
  
  elseif i==2
        export_fig(h(i),...
      [num2str(N_row) '-' num2str(N_col) 'figure_PS'], ...
      '-painters', ...
      '-jpg', ...
      '-r72');
  
    elseif i==3
        export_fig(h(i),...
      [num2str(N_row) '-' num2str(N_col) 'figure_PV'], ...
      '-painters', ...
      '-jpg', ...
      '-r72');
  
  
  end
      
      
end
