addpath('/usr3/graduate/valpasq/TSCode/Tools/export_fig/');

h = get(0,'children');

 
export_fig(h,...
    [num2str(N_row) '-' num2str(N_col) 'figure_TC_'], ...
    '-nocrop',...
    '-painters', ...
    '-jpg', ...
    '-r72');


