
addpath('/usr3/graduate/valpasq/Documents/2016_ImageryEcology/Plot_code/Tools/');

h = get(0,'children');
 
for i=1:length(h)
  %saveas(h(i), [num2str(N_row) '-' num2str(N_col) 'figureCCDC' num2str(i)], 'jpg');
 
  set(h(i),'Color','white');
  
 % if i==1
 % export_fig(h(i),...
 %     [num2str(N_row) '-' num2str(N_col) 'figure_Hist'], ...
 %     '-painters', ...
 %     '-jpg', ...
 %     '-r72');
 % 
  if i==1
        export_fig(h(i),...
      [num2str(N_row) '-' num2str(N_col) 'figure_W'], ...
      '-painters', ...
      '-eps', ...
      '-r864',...
      '-q95',...
      '-nocrop');
  
    elseif i==2
        export_fig(h(i),...
      [num2str(N_row) '-' num2str(N_col) 'figure_G'], ...
      '-painters', ...
      '-eps', ...
      '-r864',...
      '-q95',...
      '-nocrop');
  
    elseif i==3
        export_fig(h(i),...
      [num2str(N_row) '-' num2str(N_col) 'figure_B'], ...
      '-painters', ...
      '-eps', ...
      '-r864',...
      '-q95',...
      '-nocrop');
  end
      
      
end